name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) JDK 설치 + Gradle 캐싱
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'     # Gradle 캐시 자동 관리

      # 3) Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4) 단위 테스트
      - name: Run unit tests
        run: ./gradlew --no-daemon clean test

      # 5) 빌드(실행 JAR 생성)
      - name: Build executable jar
        run: ./gradlew --no-daemon bootJar

      # 6) 테스트 리포트
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test
